version: '3'

services:
  employee-api:
    build: '.'
    ports:
    - "8080:8080"
  employee-database:
    build: './database'
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - "3306:3306"